travis:
  secure:
    BINSTAR_TOKEN: gRllPXoQG/BwM5Mo1d9kdumeRz3maiNJG5xkVj7fWb/cm0a3W94kmiQtUR7TLhv9OsJ4WbFrS8B0nBASH7YcAsY9pQROjFFNYAW5/hmzbkOwYHmg8kRVxrntY4Nc3Tct2VQZteppeB2o4itZp3E45/5RZmquy6mJgp2Q4y58rLDMYGSasrgbAOpRjL9H9VAIz4bVXPyKJBth1Ik0t1GfcDh0ZIdnXilxKcNBXTBtA+iP0N2a7GBLlN+Q0AL5v8a4zYRuzhjLftE1e0654n7tU2UE/3+/4q42rNh1+k19o2KBlyZ+B/uPtwJdUH/b+SQEPVbhmZjqqfmnwWZAwomT+ZWsA1YV6n7VnGjbffB6drpTJgOHK2ZIkmYh5ahjqSnCmS9XkbE4fO8RLJbTW5z1bK49MSMZ63Kc0UL1Y/62YrhNw3HUxfGQrZNCntGRt2lZjL6HOVjpnYGSC/R1OWtsBhjVDt8+1snUL+BHNFaB5ltU1RAQ5/GzSpFuaCVUPyysb0m3D0PkV61X3eiDEaTWVjznlzxLtVUeZ2KS8fWJK8GvLEkM6H2NHF2AQrb6DFn/sNm9X8lRY253yoINBmNPALU6tYAGMUJPFbk1m11LzRtGDLAVTIhAnRVYhw4UgmxXLw9G9emFdwMyiCUxDcJrwVav9I0NpUatyPcCh6ulPf8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
