travis:
  secure:
    BINSTAR_TOKEN: aP1Sm8B+XU2W6seGMcJOPa5ppCAG3ypiYDR4eK7RKNJM2DyvZa2RmupImkRYnzaIvnDpbQxjlT4K2vi+nemmvt67W+PKi/JrjzLoG0U4PRTYew1i17rXEakKweZgTdhV5yeF8RkOXgbRKjh6iPOAaKGUyiYDedQVLUFv6TaOMETtxYrlDzAi3EnuzfvgyF2g+Suypp31v0nnJfjT6Ivtw3IfYbmdcqP0UVGZzahIUgS5cHQFyX1amYbfEfIiTVDmnY5oNAuw8/3Y9M5tkgkIYz/pjbyPQb6ZRRcCfjFItHNDb4F8w1n0xEvp1b5rIB9KY8OT/Zed+2YsBiWkiW6LBVMP7wgMhV34OxYDqqZ5z7jQrI928VMk9dY9oIJMUtMoGGjMnxXgLknd1DT/hwLP4/0pfJZpmssP+vkAiiqDMS0MMHXymslVDYPbGGhVkqwqZraHj90HLnSt7wZs4qPF+0V4EHBEfkl9MpqpifxCCHxbmAxieSN+HLZ6JaIgxdVwNrgM/Qk/2cA/i8THeuR9iFecGl30vdjipVKN9R800Q70xCt7w2AWAlpwqjusRbCeBjTvL1gKd6OXH6YUo+IMVOczIeI//iL1gCeCxqSDxdxJL/QC7Nv8l8scbPLPdiSJU/Ah9SY19fHCPleGEkKHwEKncsTW9DKK9BmBcEPlfCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
