travis:
  secure:
    BINSTAR_TOKEN: otkAGKid9EidyBF9NquqAMU0ap7KURgudPiilyM6XepBxiEwKTg0lH+aB176DRkaNieDIdZvDbvM8Y4Swys8DW9+LCVtaWN8jC/Ru1kTV/0cl4MAUJKmx45clbnEVOJ5kw5yzFMFpW4Oqw7sb6LhQaLrhXbIbX3Qsvq5YDp2kLQ7NcynK9b1NVNSf79zbySNi3YxXgD5AX5V0sgNq4i/IEjdIlZE3dmBYuCIcsQx8JRYmOrgocA0ITqxZkkiCjGy7I9Tl9/R3GukeBeD9nXLvKW5iCWSEiTjLQxj4lGlfiTV6ebYqOLl1iGDyXN7sSTAduy5DDpHGEfwJe7rmbAlddIHBWFVaIwR22FcJMygWmz9sFd4M9iTYL/qVO6GqXDB2s86bxkDOZWlKaVGfyKm5R9MO8S4nPzEJkJYYWIIndyLSY57eiQemQFJ+GjfFRbmXqhz5k12aLwdh8J3PUrkRNw3yanSHMyaoz5ZRnzocZg5zpXwqCvJuBbJj5sYLvCCSMABD/Ap/tMdxpoY+kDJPeGN0s3uQEFO/ZIFPmcAN0zmxLDNDviLB0ZK1ynDSxnZ+S5/vfs2MON0UT2PqQE1p+A6reYV0WI4aoi9+rx8NLquTdKbYcdNh4UFHJQM2yDVqgTj3hOwTgy3yYSg2F2OKJ68C82/a6xCQjk9TePuGJc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
