travis:
  secure:
    BINSTAR_TOKEN: Z/YxNmrgWUFYZfil6dAI1jmVX0qMfaNDXgzyPN0Fd9FI8JCbYBAxDUpISnMBHUX/8IR+ZnBqeOA6y10RJsgKjHBMOlM4pYkt88s1MfPVlNIi0wUwYCeWouA/y876Br+6ZEOBrOclvC5Q3cSzXO2BsnAtu52oMCJIx/ggzSwx1Ujs8bmUJgh0B2G4OYBUK0MzcBJt/fJ/2p1XR2Ci0fIlt8FmQ7t8s+C+ElQacNYqdZlBeYtw/0zJVyJrRhkrNRhFkm0phVEc2QZjouBxPsJiWVvU0LLr2wTu+gQd0R0PXe272lBJTwRGXFj1Gm6ma2DT9dTC3GP1G766bZyDAtgBzTIPHgrHyIjyd1POWHxXAED76vkTHAevsWTrewvXlZEo44fBYnf4vbgmUZBarVavBze+f/6Z1K3ngebx8vwq+qcSLAE+k/BKO/MPp14v9ZUmr0ghZ1/kol9ccTygX8ehEaQWK9gb+AM/s4oVkeHETLHsbphOILarRe6R+50rvMRxuhj0ncDnzfEQlT/jBqLWNWe1C+gu9l2jCqBYtqkQnSLvRtMTiQKqYChRniIP1bw/PvddlxYzs+LlbsTlEg7kVTVfd0nlWqylFSPIE3rQUXOWM2nQ3UEf5c3L5ULcpJfPGay4bQ+C784CzEhGmYxa2qhAw3LcvqjOOJaoyvJ1cic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
