travis:
  secure:
    BINSTAR_TOKEN: up+PaIk8pyreUQxfkiVVs5juVucUGVLquAZD97+UfVSSXb1Jh/4r0Cn13/fhpZoBeI6K/CWOPWrErg3P0ZW9CDblHAgjD67bXzO40jmVUNa/cTWVasLTOPaFgFO9jFYBsSaEwNEtp2BKgNVWx9gK9kX6dfJOgFdND4ftw1KOkHh6SU3i5VHF+KLlyE3FKBvkF5qzd3YZ00nVALTBNer2m9U3hg6jSpUXF2JrAic0r/i5cw37+hUo+7idA9v2pU3nm2ylGGkID2SximCHotFvMEUZLdHHDlbRx+yS8/MaGB4ueiOcmemaeGlqiDIECDdmUzBJU1BJB0GRau5S4rB/DgpQXvd6sJ/ncCW2iIuEyP0FjMv9FcntcBRHNfz8smYNx9WugeO7CgzHlsSvmj7TATUKvMazfrf+I/iAmNjC5XutkOnVphvL/ubgT0cbi0YqD8RZjFg4GHsBEjRiGtC/oSqwFG4p2W8+/UMakzlTQwkYNSfihdmSyZiWbQyTa+B2bHGRrfXz9GBDzIcwiu6aWqm2TT99ylk1fUxHOho50psGwrrMcw4ZbhVJ5/qMKCmco+/NW0dOWDes8vfKQjcS3n5AtbvSqVkL7E9MU+6URxlDueU6bm6Ar3YfjxoGy7D+ZYufADms0B4oAellGSXLbOmYUJlXeQOmSfhUq1rLiWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
