travis:
  secure:
    BINSTAR_TOKEN: vXKlBZDvNwlSqIVHoufy1ygmzm55jTfmC/BcaH4ADDowFkLdK4Xrz9CDLkIIPrwmXAUenX4UjVYIDw98OW8y5mUCF3JefQMCLPN316KFCh74nXEZeOussFGtd/7mZv9PuRcu92NXXFrRZ0KWSeLIKnreESPYbWn2KgTue6yWQmmLSD1dvSpYkBC1dkIpd/4vBVsAT4S/9GD65kZNDoQ69AxBLA9ArY+O7vhCdS9/1pulooGOlMkKi/+hcW7WQRlIUUXQ1XZKAU+ukdzdJHIfUumcXbRPHatY1OWovtHz7Cyf8xPRN6AOauW+sOIfJUj3SCfwM7ORsuTv7jtacqM4eJytazsgEJoDkFin0LxQTpceM9QLtkMIrR9SAmRqH9bmHZU0JrJPO1Pnj8yeKV8YotL1Y9/V8mjSnVllmFGYqsG3y2yZ6mqVrG1efqqvItM9q/dlpmEgteXNhUAq4SLtFfYpa7Ol81HRj8LohrcwBb7gdUMPbjGSHconPRMdKubEdV5uV7yMLIyRbEegct9JHI0YlDzLMHzYFerx/ZqZRGZIkRsKI3x/pLx91g+5cCcTmlJ6N3ZfanHOS9dFATE6JSKZz4AXLKnOW4j1rXsB3hnl2EW6Dt4RN/V/E8PqgJSCU+vdaKd4bNiWvvtBlGA/HjTpPCOQVJAVYSh603U/ytk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
