travis:
  secure:
    BINSTAR_TOKEN: 2fIYNavjMStjpTvsR2qgKBB+4PDgsBSZex16xbNLz/a636pUXlZE7Vrhpz6E9imx3MO/pkgb+XDT8EDsHJCrACCvtWpJ0KS0pqe2tajMdiTClsgpm4h5PcWS2aPrWL7mFqusZK4hnGCHGRTJfZy5KE3S7tN9jXvSHJkZ/P+bxhPE3LjzqY/GTd2o6o3S1bpbIyOC9FFG8TgtS8/jbUVewojW/vqRAMd78o/IF9xcff7a5siv4ciJiMUW1yIar691/S4Z5B2desdtYEj8fiQAvx5YrFAG6hnM9LLhKn3/pHVi5jpb2V7k4zAy7fnm45X6lAeZhzTDh1UeGyl+8h1WCYbLDNkKFTpjKq93l9RylbUDCrTRiSZoZNte+/vyUsbdC+mdynrDZnkdncn8Aby91QB6pF7Qf32ZEmtxzOVRUpyR/u8aCl9KHT4i7eGuUo6TMBdCaruC0+k5Dfk4G9jNy5C1FuQoWgh0z8zMHMQm59P42HchTmRT7RNFNi6ydOIzk58v/Va3FUAmxBszbl+ehYgPd5PPEZGzxMusZsgov9UcYIGQ00Yh1fqtFxaKHwABFqWfoHo8hFHMXktEE7M+B3Fgy8kcHHhknjpbHFux11h/x4QdZUgU9YOiH/tn2Ytm3AW/xl7Y472VSQYRose8dMIqfv2vfg6ikwkK292avsU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
