travis:
  secure:
    BINSTAR_TOKEN: B+zgnnIz3nWO9q35Abgp0us+OIUmBlw2XxZL1V8y1FlEDhN1M0S1E4m1nE1WPVnHmj4tQ5RUC8nJynk5//ZTItp1ZHHhmnkEuZ3A4aFUul+lzxiBYwOIJskFSyltmf2BJjNASN+qp6WEj9O2WarlRw2V0KhbrE0SM5jKhrszyHBSUWF6GE2ARvUi2DsfkN0qgG1Z2IWNHyTF5Ta1fSFCbUuwKTNsHsWojufATDUlfQhvKFWVN1U3EDf2UPcoh0L7FGk3yCbbwYXUZifSwLLKFTGIWqC97XVdiReUZhr2eoWIcZEbFxVOJH9ddv/qldy7FDXcRzMx5/3c6nd9uAv9fJAibJ3b0VogrprDDB5hiYoZuM45h2BVXiF/8u91OxJIlW+uEsq5syYCDspTGQGDeDr3PoX5L95ybZNL4C1cn/2qZGsDgRkfbjq3PHFPEgT9dB873dWoiVqMMtlNT4//qlrn7UAFj4AfJ1H9GXfMjxdrjulMYVEnHBZ5Siqd35x0dmhT23ToXZ/BJccXrbL7hzqgpxZsSvP2uRFEk/vRJUzSVO2BzRFiBTxMEb5/+nfz0vqBXNVtZCIGQmwcdeqq91s1wcI9AQzEo24eQucg87PBDWakdCzoz37tciqusIruFzhoIWj9q2P/rnGeJpk14ZyPdqVm590d/OGG5cIeBcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
