travis:
  secure:
    BINSTAR_TOKEN: e1ANmeEQ2A+AfBfrNg6F7S/R1Zwox6aLtKURfrxlqjfDusmpSL1HeXCLVlcnd5kqbxcjSIX04lQzTL6fz3yFaqMp9rbtG5jDymeA9sKahw3rKgFdWuXSTUwKpsh43+QzErXb2V7OTyLod8L4N04v7/Wg9x5UDj9b81KJsl3VW7JtCNTBUZqJnlG0v3J/R59rGWeYZ2awEO9+uvFbs9iOHxhe6QiKBfnfLkbGnzUy6aU/Mc8u1OxkSOm7IhE904QPLbyqQQTp6GEL42Ve6lexD3Unh1BE/mVZu/Z/gqZ4fXwMlZFMG5/lX9CEriCG3EzHOvtIESvz2wVEyhA0Kj9J48NMmzu7L007kwbJhHhTj/X0c//V751qVnO6m3PtiWjeMoo/gg0wMDKNLm35PIW58pY+yEyUuG47TrQ7fnrhl17ldLjM4dcvL2yDQDcWEcKp5a3G1D87ALWgVNv0+bEkF7aSdoGkTABAUJmyzXf71lsG82voPd4S8YTCwUbOqg11+InZ+lCYt+7uEtoGtxdF0v/ROSfuBy1Hm+yN63w5f2Hjdniu6CcvDLrdaSXuTwE2iPUevRmq/EjY9ohwhqDLQYDeQ64aV5pgQlUw71MTx6ri/vURFUFMKSdi7dkizPqLSggoWL/k+hXqjNve6HoyA91FP/fyO2JPx2C15VB6os0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
