travis:
  secure:
    BINSTAR_TOKEN: f4FEgQvb2gnX+Vv2nqv3OJl77wNpBZVh5ZxdspGH4OcZF0ZLVwX+0yfbsfcoXetpBL981PliMpvyF/8IYTpcymjBgUEJXrkA4M2djL2il6rp7zfC989TY9/6uOEefXnhfkQKZBDSznGXlwq6KQl/eUXnOtv7TB13U1WD5msE6mb/iIPPzKx992kLBXR5kyZzH4DuTPzJa7S1YsNlBWRY/R/Rrk9KTZnDpq58jWMjJH+IsTqnYMzX3QFSv6OJVRGRvBPiGG7IHvBOD3Fn/nuPmIxlMR2IDy+jemSfGLFAPS0/C9W747sunvI2errUr9DYz8gEAIhC7jDUDFKgIWGE3da9AOSF1ohniGqBYg/764TJLlSUXgS2aZCzeUfi+avRF9XT2sr2jzgdPwi7FhA7ZywsspDffiq+isHy325fejWoBqX2CmhyLKHZHNMZ5ztkR3Uy8Ji++YvcxgblEy3RdPou3x4nJhKz41ffEQbzLo5UmRbue0godTVrLPGwkGtW9iKsLyLFbqIfchG9z95ulCKL5KoCCtw0SQwWoEFa821uD87lEkX36JSmD5MDmLI2k8nwAU8gqt5ZxyMmxifY030WpDxna5K8jzwoa+DFFPT1TsKIvx1Ooz5EuyQQ4JlYVJSdpoU3que7C/XqBqKsZzRSQeAjoj7O2mofnUL8Xv0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
