travis:
  secure:
    BINSTAR_TOKEN: Cv79eZ5gLiIcZOJ2ADp6JSOzI9NApP/abOvPfWk6FBcavd9RVO6d4v3cp3zOmrmwVyQhvdaD64nISwH2ZBHRHpngDufbve0QJuPm69zhgf/2BXPBsYStNUujYUs+Xr1kT6w2RxAVI2GUM/reCWp3nYGRBtDzal2dpt1q7VhJXGZjAdVoMYUB3MLeOe7fw9MMF2h7DenWqKEjSRcgZJJ4oGYUAwMTXqlAC5PYRuPDn04DJ896a8W6fKaEeTRx3oPxxKnI0P2AQ+Dgan7OIEAwfnl24zatnhWeFWCd91xprgz5wc2n1b5+fAvlJqAM1R/jOwgKcQ8lhHFPD4HFsWgwkXoZgBhC4KQ6kyAI9uWRKLWYijPdZHWkaeyGmR6OJ4XWnnded/QbmtXeO/hvEGc7hyx5I60lwKze/H2QVGp6ceX7pYVuVWmVhUvsQQ5J22g4hgWwp01epKaZPJUFH+xhvIFDYv15zREVL8oof52DJ7naMRVdC0Tw1StTu49mU9PqjTzAz2oqY4dqYZbfmanLh5V1yTPJxuQb6PP71UtMaFIKsYcFq6JG+jF88/+vEkShOUrTMce5+C4jDIzrGIlPxP1CmzIXjMyZ7xaxnS8UDcXZTg95hjb7UQqI9nqseM6+B/tgnYgLqFy+808/s8NjBmPRZyf6MXGoc4xQjdrQ5Hs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
