travis:
  secure:
    BINSTAR_TOKEN: T9/lT1uCYs9wdLIr0V++kh66t3PIjlHbHpLE7dWpzepGTYS6M/aPslvadN7M81jMfFJrOJiMm2b4/oibhi58JmbiODaZQYpzQ1RA3a9wEcEPHizUr9Chif/qUO8g14y+ug9/rohhC4EJ45juLAaeLs3JPNFKlMaxGjrvWJIK0UVkLVG8tG8gHpersFTrXPwNsffGvns6eZgw3uplnuY6tjFTRlfAQ+kTilZETZu4KnlyI4Sx8CZHrI70PNfLJrzqEUgHstyUzRgHXB3OsG923joI4FCXM89GxHSw5o67t0gqkMynYLIapfufs/jew34jA6i9zjwa+D/1IHm+q7k+exruQmvUEfiepmPatkw+FELUGxvj5MUGZNdpByemPbZT4PLKvLEKpyHGErCPJxUaKAfIxG/1SNDGDMd+qcmSQeupOSGqEV539UVr4GlZSh2uzIvQ4wuSAzCbKnPkMMdIwlXXy6n1L79I5lr5heBai5kzNEhNx5r/9rHxIoQTSqqqg9bUxV+KZz9vnkUhpxz5MCvbvz6C+uH+GKNbRx0g/UgmJAurNv85l4lVODVPDCGiByD3gYmGqH59J80/prxrhuH2KFdzO/iQARIL0bsKI+pOVd+9g0QyOOOocGBs4+EUSGeCg8di5zqI56vqt0A4Dd6nW/KxutkLYJVsDVaj6K4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
