travis:
  secure:
    BINSTAR_TOKEN: PS6jg+Du34fF8ONjcUUYeUVX3o1DECu8RCaVndt6IZaS3x++rh9pJIAzFAkLSb/a7W4qrGKzFUvswz3kSRWRCC4Qj58eFMMzXVvsI6/+YN1ZpQNshBmn7b2txrHBrknxJArOS7NuTS4D+aFn63BzQ5lS5v+SKVx0ft78JbIxuoTGGvkDdH/GduaMLPZRWZaeIA/lTJR/4uq8BJT4xdRwYhNHSczPnJp4dmvwF3OqAhtDFk2/3OxruiZQJB4TTj9xc4/JrcL+UhwW2IYD9RBNEr0ZQnTbty+9jkTq7y4vFzqW6hZWFm74boeEYXq730Icy/qQFw7eS20S4IVY7BC7w2ZVlidW9ELowJUBU/BjviZlnI+FEpEpFTV/ycLHaCbhSARoWqNyKNZl1fMIS6xBzS1/IBMCc59rvXZj19V30ZQuSq2fiZy9U6GzQiqrpHcA+aUeaivczJQwka8KvQ6M459yLVJ5Hbey1/r9xMubyGfPtWSxQ+s7eLbs7n46q+D0modwHrjoQLqieBE9jnE3eR1ryCkPl1ondWAPLKPUTR0epQgrjhaLr08SuBpx4W4BaMO6jtwvaNDoIiy4pzDTfIhNlQwoxzL653CFcZnGkQt5ZSlo75mNJk/2du1PDK3qD6zrdxlG7x7Z8MjezacMhL9TVhyjFeaFRgMERV6I3OA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
