travis:
  secure:
    BINSTAR_TOKEN: zpn3SN5qA/IiUAaJVu1XbvusRfybnQ6iIQxx06VIvLxUVnNAlZ6yT+1I4l44aAjuOJD3wAR+2BXYnd4mwL2L8a7CVow0Rr4ZcCELDM71KJT9Y85mU7vaSezt2rCrEBn3YTdHNi3TeZ8sQwsVtmI8Jqq4jc0NItE7MqkppdQoaeWNLzYkrTkphN/yvXhm/BR4PE6jT8Mkptow+gv3bBTfBgIX+KZ/TyewIcal5vuK+K/eLzeeq19fbzTihsJHvjo4rGitvDkfR4N+6ns944LvJ+iSwO6wztxym73jQNGDYQ+wJPAtpIpJslwHpTcxcSTSL9kRt/E1QHxMKreffhFgfM7GMFA/fibZIhmBWc3puqD1HsZ7/RuvXp6Bl/f+E7llmP0NqD5hmlAp+H1F+NYNvqsptP+Y7zZ/BvHA7SiHRSxDwxgAa8VGaZh8Q6ZywtfMQWEKm7IilgIud3KB4loSnXQYwIYwNtvmbDmjtEC227sBE0TbAkZlE7BNeH6tDaXFrQ2tHKmWn/Ai8EA+J/DHDeHE5wQdXtSeWtOrdIQa7LwvpOzZFcPeX5OA2q8D0H916a+TLKKE0aFVtIk93MPO9Eqq3+NiJ7KnYXt77J0Z3gTkTISeR3OOrmLhDhVHtIe7GiaqUmfGrLvzylxc/ALIvRRKHoTLI0tC/UFVtUsgi44=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
