travis:
  secure:
    BINSTAR_TOKEN: IU8uJo0Ws7U3pUPK3ZjhWn66F+nDO90i4gswK5eEJI7pBzYaDIP8UwVkEVL9VuGMEdOxG6bN6HbF/yMFy14guWrJws5ipqUxVz/so9yX/0YUwwrOSIbd4Rloey1JZeUflxE78DlOBQgthPbhxx0tr/zZa5yNVdlaYBVV1zSkGqXwruj9ULHw0QqIjq/6NA7H9FcWdWXhP+b/Xvq5OsjHdML93Xxztgxq3fwK//bqMv6Pnn1cZ3FLcxRCmox+G1kRDTvfOEQxQGuIa2X6iMCkHNty2Zj9M/dpHyQulLeHk9K1Xzc5yuTC/hfdHHYlyGz6l4IKgpfyrPqdphMTZl/Tiv6lcc5Pt/LIkkX9fWz8nKvrzzhcdsiTbIcG7wfWIrEw9ZAZUabiVqoLnKrTFYNJ/9eGISfkOOVKQ2FxANXlTRLA39DltwPV7YBqIIchtZNTwG6bLWy+eLrMZm8ZIA8O8k0s8HIX5DGda29d4qOClctxO3mitlJlsUkk9jql6EQukrL8LNqG0LWyTeq5OhItGbPk3uyi055V/iL0taiIxdTG+Fb/iIbguATnwALFBCaJUR/v9CcCZIYB5k9VIMmCzCIdAkciekxab+nDLzkflTZLew9Gn50c2jjkHuuLaL4kWyV8cz+Rtnhgqe9hYo/ijbDUQfNCG76of+dvUFhthDk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
