travis:
  secure:
    BINSTAR_TOKEN: SrDPnR31apIJbeQvihCT6DmJPTamZnyZlnLSNBVDe+yS3L4Mn7tVfDm/OE4bFIzUkGYJGACud+d3ON/CN35jE+W1z4dT9H6ju9GO1XnClcBvPvNcL4xb//irAbZuBjCLk/+fdLiFJoOPF4isauxfgHSb4iR9qsJEjeK1wPbYD1Ttfx+34ftvdGIaEdXhHNfb0bwtiyHXWtpQ/hd+UGWbiOop+V/dmqSCWi/7eCMfEb3ajC5QsHCFzPB9cN5s2x8u4/xeERlazQH2dfWMMOpD7CV9tRPAPywzyesxZDMs9UUfuWIApZ05kdzTH2oq4uVtGCljzVSkWO/cBk37AhcClihXBUig4Lfx3B9M863mBqWSYk1J5W04W222mOpNNmDUSa7W1kdPd9JnSD3rU5QAFTjia6h2eMyZc3bVAcivl/EJIrTnOjZaCiHFUgYvjma2CY03J3nHd97ckdN5l7/hTiEvy8fSkl3I4QOK4MalzYE8l9qSRCa+V/r9+2QzbxHTGlDEpIwxB7GeYj1KgHxfdm/UjlyHq+kEYa35sM4GVIBjZ7OWBJibXyvS3ZP9+JMmDw1DgFCuUI1/uTW83gNz9IbirSCFVEbf3sS1Y1/6a2nWPN4d6vBeumOuNzXQwJJABaWj0Tbqj39xAG10H7rh49+7tH9o/OW3rcITAbqmXEA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
