travis:
  secure:
    BINSTAR_TOKEN: DkXzf7+fNLaRAhboP3JpgqspG1yNE7GRKDBegXQ3Hiya52kwqHMfdQuPjmt9xvdBw5NBcuxWJWhcK8YawpTRuIcpwTPqaNGK45W67uqyQjZ6s+5JvY8eTGD1p/JQHCx+BeQq64iATFfSrb1p1YYgU1Z+l2zwm2fmoA1smY7Yzry2lZHhCQB6v21jawCelnlXBQwsSrXrbxU3FgfAhAvTfTMROc/I+UsO4V7XTdQlrqhQHWHFmauEkdBd6xcK7KNo3IPSMKv1k3wZxJRf5qkLO8Ly7lBjf6K7URIMTESXzJcxhqC9WNh5JAqcKolUuiFVk3ubupRjsHAJdoy9Z5+PUIbvny13Yf22ADqzkZf393zE7q/brIL7QwgvWlL3cohPo0vJU3rwes1Xe+kMeSAw5UzmPx4OjkJhrp09o8HRlWEZS5dhdJ3HUEk6L+zdC69YzrBMsJXQ6zLyNd33zBpf27b9eIB8K48r5mK3nIYnpeXwTz7fsoQIQngQG81p+UgmXcNksxBHplQ6Yn5D/NRC5NjBUkhZy+rkBc9tExUEmaxil8XsATEZfeMnD7Zv6qWFpace42pyj3cSEhAWC+Bd9RDhy0VY8hsN5MtGy3drQsMXGNwi+Sy5ajD91qoVYAStmFDvdrHKPfOloC8V0pyWqJ7lIzrXpeDyy2QrdjWi+zc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
