travis:
  secure:
    BINSTAR_TOKEN: l2qskgCeWOe+pIlTQEA8ybijxyXCy2auOhDJzJe4V4Tt/3hUkNcx0H29cJ3CJI0t4Yy4/SNf13VhCOQez6sLE5P4eLUUVZne+3he1I7TktIksi8ZO6gJTOw4IjXL595khztITIEHqpGe8cI6ugXBvmlcOVNwDp705eHvS8Na3exIuDFgivcydYCAdcm1xwGmqCCqUs4k2911ySVY6lb3u1vVGBGACsz5QU5QMOsUZaymf2jQt+2x6tDq/XQF2+UwGKPE2N6ntR7YvcOrXTlUzHoyvgWHoh63AIrKB7c1h4h+r25CqVOPDmN3X/ftEZM/WCmEkHdNjb57l2y8SG/LIyZ7aHyNHDXIzRsp20Ky1f7yT0j1BTZKHaI5HBC3Z0ccPXv2wmdC1RRJoyxJNydsrxWg56bX71vHZqy5RnPczk3Raj2LdnnSbBm4odNxTn1QyGNjTM3Ktlrd+OdwjvEGEKo50Zfcy56RTL57pUMqBYLJHk1SHGkO62J9KBEIYvFHBHcetjgWjLc4sBwU5ttubR7n/8WkJRwD9/rEgY2TP5SsaP2elnBa2EJyenSrmwetviqcED9SuIpFypgcZ3200WPpPrL3z7TUPW0ILjwhCdPfWTisMQ7sGQnrsZASERrTu8zxMa/TsJxxmevxEbw5YJm7kK7Ar0KwhHnKdeUXPlc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
