travis:
  secure:
    BINSTAR_TOKEN: XYwy+3znk91ZJE3RFw7m1dLS/WSx+rD+RdT2SCnb0u9Ylu39V4bUQ5+0ckGQ0SP/3/F4rpK/t28G7FygaISCj0YEqnXfd/+JNfUaiTwHDeAN8u7tMqTnn/zbkywctfgwrI+lqJ2KYWcbKsCKwYH4Wo+AvcQ+NIlIcjvlgkbEQ4hGtyQY67eu4seB3ZCq65lEUK9hEZrSO5JSA+gMNFvTOETFSOTjtakebWlkfGV0+Vhlfzcxlz2mrnC+DQ/TrNSaRiNIU5LP6A1uNjlJLYPraBilksEz05TJEMhhGhh3eEfg9ZHXQ1ldsNlUeoibZ3ZVHhu89XROOa2X5mrVQbUPOVApMrCefRECnwvnDPa8t8lOYsig0lR0E7u7F+thRngFHab1nYptaQqGbt6cAohju6zV/VyMcv26U1dRHTcmjcDxUyTVs3pCQiaZM63MolWi8HX0hRiDM0q57WhSjcqSXJFzux1S3B8b4Ee89xrvSUAXl1dW1F8gy+asPFzuGuuh/CCpfLNDJvQ5CR/2qZwRI/27niXyHAUs+8yc6GOuAngkRgyjaEZ+6257gv6Owzz1drpU69IBxYd7CTUCcsyy5xjnH6zlXMJh2XFB0o/ro60SwEoKn5PU79Ri55Jybii5pMG/+G1qRVshGZsPZjUOTC4TUIIDecDAWn3XmxzIVkY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
