travis:
  secure:
    BINSTAR_TOKEN: h4fnpZMrhsjyLRblR4PZFal8ydhfTGNnY/nltp8RkVo0MqyM4tjaKLOAhAcru7bnPPCEchCrh1x6D0JBkL/40V56JY5cIdyeMexxVIkpHa5Ff8EGo3EMfqZ6AIAbvTLyHp1uS+EZPZvzP/O6zqQKvEO1e3g4Dkggn0QA+Wd0mLP6OINTjzg7j2RZ7fR/0HBEydcke10JRuMSvf+h+ZweLfGD+bHn5chscmMY49dgunrwuhshtHgMlSGXytRGWt8/qec2pQQaIV2v37q0UUetoTQVpuxctBN7kCRcGyzfUYOA89BGbwpVJm1hjbKdISOROi79WogSGOrDnD21OOnVAjb5PsIH/i3GOFSeksoFWHHoLGsaYGlXj08gL0GLN1200kjGnRM//sDb/YYGPkYcyXLb67glIe1TLUSISwa9Bpv+JgYHgmwfa5KUr/sKP9tOiSVW2igqgKE8o83t0D8bn1tDZUDAZXXc1Z/GqycBZh5XQHs2lKsrDCG6CNn2UnvB0mqBJV8GtCZT9pIp5vrDlso5p7RnOWEx8rfMlEzhfASQxtMHxBZ5QluiqM5NMnlirqst+/HVr8un4kt54U/QcJLG7KqoY7R43IKTNjXBad9XoPnuv6mIqjRaP3Gp79NEXdOdic5K8YM/sLaU01bR61qCHw3s+AmYDuN1/Ghi1mI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
