travis:
  secure:
    BINSTAR_TOKEN: u1IDy+Wgll4gDUrVETF+VJ8daWcVfqaEx5F2Zi6HpXbFovwmtdd1GBA5/fdORCbzv5Qt53jwqE3HKeGdq6eCC3gaSmqxXA/RdsMxi9xIwk8yf3P8ZoNeJUASN9l8T6Ouv+2PSJBdEZq8/Wjo9SDHUUxoT4NvxlK2ybBhEUzZdHFoFK3rxHQWbCl/BhSnkeb6VcNQwqLn7aWbmbT7DNgzY1JUMUodovuQ4M4fLqedu/jsx9g++q1ztItPx/JxJz+kwLxnquO63Piq28eHK8bWSHgrdhngXowXMCGqqHNNStgV9rREKhO1r1Mru5eqVnrpg4BU5CjHK4nMO/nU6z1njLRkJvsgxA5+6AlLRYxPXJrXR1AK1ghOQqB3gyDJIdmlqV5tlNVPAbWdMFDDQQcXipAPgiEkBzh764lrsTpukpDVFnVDTOUUwNTVlKbRpVQcKiDqqkR9brbIvIrL+BBAPCXwNy9T606y0WyoZ8YygITwIRYcTGOOnIxZ0frepO3lllGFS7888dmOFF2ja3WB0kzO5wiY8GkbDlLZpP2+6hhfEj9iF+4f4YBeocaQgjVYnduQu7En6zKL614VkwTOK7nx5/fGiqsCADP2833pSpe4uDQoh94OLCG7GiEvosfPY69yboOkWRB4C2qugyi4NGCJMqt7hArcC6TPF49aDc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
