travis:
  secure:
    BINSTAR_TOKEN: RmZynzomjiOaHLmWDxuPyfaBDgT09RhagK0Vcm/zClzYppHtX+lpGQ84tn00QR4BOp1yX3ZkpyVLj6TaJA5q03YM/LoheuQApGuk0gGipt1MsqgFhIwm4WpOHQAmDEE6LAY4pgJN2tb/hl+xrIepHVGdoePSBUTSIXdEErgDeGnYIZNNb8MvcI/JQmuvOpqzEEFWB0qrjHC542w/YOkmCMa5cmYy9qPBPSMGQrvDaqQx29mzI9FZtXU3HlgBqpQ+3ap5V+EDwBOmNOHLiOnGnnGmV9kOdqz8qqxe4k2JPyDbsWxAA+5iF086fx6Iu18dLPvXt0WTPhhZknDPxnF+fgPYiOFCEa9pePoLmtRmN3dSGRf7EO1jtE2DOiMCSB0KYYIHNO41OSfpHSC97qR3cLfEaw+hjO5EKdqJe6tHLuHpyjGLQU0cAXsUPRmygsqUGVliSeZvU/lFvT69lDokLQCp0CtDoF+SyXJtoV3rwfppduzzg+KL3oiCwHIhCuM5tiF7uMcyXjDRHehxm17VPPAloQjnV1zXJT+Fcjy9Wfj7am6dKOcQvblqGEvDRCoXp7GQXXBHN0VI1BwgIMmWSIghjf12P5crGl28F3STU4SxGm7rgXApStCqAVFGKGm/+4ME2pJsCmALMF2rGVge5RW8H+eQAsENmR5eANQKqXY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
