travis:
  secure:
    BINSTAR_TOKEN: f2KvwCUC0ln3yxyQWSXwHJFioYwOB/CKW3xa4izrzAyqfZUHPaV/F1XFFccI6oiJsI40lz1wMekG3JNb4c8q71EzV8/6LpUe2/731UgfMTmZZlmg+zLfXxwg1vtGowAwcw2Ks6FgY5eiYGJlQXhiPIdYQamkNVQkHLvkz4j5qYfTjPV0MjEbTK4MgZjSDwuyPUk0OemPeLlah1cph7GAHOR/DW10d1i2KxDv+A7B5Op4gZo2hna5eaD7KbqRo2Wd4AsfuNnicVLldTs66X7M0CqdvlHsJzQgIsSSWuLiMC27CYG8wB21dza6LAao0hy7hZBp1yC/XxhT2n2Jgs/Pg2Q6FixwzaloZcfPr82rTzhGblWUhaAW37EjbV0znJPV4Vah+PojjbN3h2VqiZurTn0FCUlm62edNuDjpi6gmz1f5CkpgWvKZL+Xjoq4dykGHAHhucnBE5ged4yxZ6r3J/AfR7S691RYlff7f34IgACB8bFmhp14zsBm1Lp+vW80QdWsp3OiTdEFnMET3kzHQ2O6hVhC4vgc2EVObOPZpHpNtuecJk0xzLYf/gMy56UVq2YarAcMXXEtGfnq23fpf4TLCXgz4Swjnqd4DVj06oo/dGlHJxs9rPEpneCvj7BtrX5kFl9jAvaCk8NOazVGcB3VwufQcs34ggBo6tpw1oo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
