travis:
  secure:
    BINSTAR_TOKEN: ho5D/V7BuATK5g7XwRRUGt9Yk8oYaE1goppgsA3CNxqtce30gdT+URxvEiOaUny5RyDApJno69SdRpfiSZrL4SWy/A4tgccjf14FhCClro/9xYCGMg2k4rdMATDPZMB2KCrGhaWZ9VBPQXvUomPV3Z64GW/mbLSeAWEsA8kHkwTeVzsvb+Od8oKArBlZCRal7B6wnQjNXYfk6mhopo2OHddBDEBC+UMCAjTESrTIH9+FaYJqDeFlTuTHBsUzOZEVGV7ZtvrisiA8/p/3MbXFAWqDsRm8tX/xXi58mhXSKTdpPhz/CDqwKYAxBrTbdmB/dMUZGFejoM87TQNz2NoDoILmDg+fyEVYNrNAHkHs0YjCMXdxbkhg4fe1xBPXG99ozcfJBzfRNuAkAROe213EcVYQ+tbCDEJmq8hQ2MRpkykAh7gt79CgQG+wu4BeB1IRNrz6O6QyjcgT0w9voxT7Z/sFA8ThvWLKVqrzEKEmIMeHH3OFUXjTKIml5F7Xejn+/ZCZHWjgOOIkurCJVgirVVAZ3S+Zw0h6w80e164Imi55NTliOMnzmUtEFnfzWzK6HNfbAQeVVCYB55U6XE5Lnvlfav7tBzOZJJzkjmnoXuska5OkwfSdtqmQkM//mCMudeGY1YUl+1fi5KSJjbHAQCzYkQERiTQ6La3Xr5+ST9A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
